server:
  logLevel: debug

template:
  files:
    main: file:template/main.hbs
    header: file:template/header.hbs
    footer: file:template/footer.hbs
  title: LINDAS - Linked Data Service

globals:
  datasetBaseUrl: https://ld.admin.ch/
  sparqlEndpoint:
    url: https://lindas.admin.ch/query

middlewares:
  assets:
    module: trifid-core/middlewares/static.js
    order: 0
    paths: /swiss-assets
    config:
      directory: file:node_modules/swiss-styleguide/build

  static-assets:
    module: trifid-core/middlewares/static.js
    order: 0
    paths: /static-assets
    config:
      directory: file:static

  rewrite:
    module: trifid-core/middlewares/rewrite.js

  welcome:
    module: trifid-core/middlewares/view.js
    paths: /
    methods: GET
    config:
      path: views/welcome.hbs

  ckan:
    module: "@zazuko/trifid-plugin-ckan"
    order: 30
    paths: /ckan

  entity-renderer:
    module: "@zazuko/trifid-renderer-entity"
    config:
      labelLoader:
        labelNamespaces:
          - https://ld.admin.ch
        chunkSize: 30
        concurrency: 2
        timeout: 1000

  yasgui:
    module: trifid-plugin-yasgui
    paths: /sparql
    config:
      urlShortener: https://s.zazuko.com/api/v1/shorten

  sparql-proxy:
    module: "@zazuko/trifid-plugin-sparql-proxy"
    paths: /query
    config:
      queryOperation: postQueryUrlencoded

  handle-redirects-demo:
    module: "@zazuko/trifid-handle-redirects"

  sparql-handler:
    module: trifid-handler-sparql
    config:
      containerExistsQuery: 'ASK { ?s a ?o. FILTER REGEX(STR(?s), "^${iri}") }'
      resourceGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <${iri}>"
      containerGraphQuery: 'CONSTRUCT { ?s a ?o. ?s <http://www.w3.org/2000/01/rdf-schema#label> ?label. } WHERE { ?s a ?o. OPTIONAL {?s <http://www.w3.org/2000/01/rdf-schema#label> ?label.} FILTER REGEX(STR(?s), "^${iri}") }'
