server:
  logLevel: debug

template:
  files:
    main: file:template/main.hbs
    header: file:template/header.hbs
    footer: file:template/footer.hbs
  title: LINDAS - Linked Data Service

globals:
  datasetBaseUrl: https://ld.admin.ch/
  sparqlEndpoint:
    url: https://test.lindas.admin.ch/query

middlewares:
  assets:
    module: trifid-core/middlewares/static.js
    order: 0
    paths: /swiss-assets
    config:
      directory: file:node_modules/swiss-styleguide/build

  static-assets:
    module: trifid-core/middlewares/static.js
    order: 0
    paths: /static-assets
    config:
      directory: file:static

  rewrite:
    module: trifid-core/middlewares/rewrite.js

  welcome:
    module: trifid-core/middlewares/view.js
    paths: /
    methods: GET
    config:
      path: views/welcome.hbs
  publish:
    module: trifid-core/middlewares/view.js
    paths: /publish
    methods: GET
    config:
      path: views/publish.hbs

  ckan:
    module: "@zazuko/trifid-plugin-ckan"
    order: 30
    paths: /ckan

  entity-renderer:
    module: "@zazuko/trifid-renderer-entity"
    config:
      path: views/entity.hbs
      labelLoader:
        labelNamespaces:
          - https://ld.admin.ch
        chunkSize: 30
        concurrency: 2
        timeout: 1000

  yasgui:
    module: trifid-plugin-yasgui
    paths: /sparql
    config:
      urlShortener: https://s.zazuko.com/api/v1/shorten
      template: file:views/yasgui.hbs

  graph-explorer:
    module: trifid-plugin-graph-explorer
    paths: /graph-explorer

  spex:
    module: trifid-plugin-spex
    paths: /spex

  search:
    module: file:plugins/search/index.js
    paths:
      - /datasets

  sparql-proxy:
    module: "@zazuko/trifid-plugin-sparql-proxy"
    paths: /query
    config:
      queryOperation: postQueryUrlencoded
      cache:
        prefix: lindas-zazukoians-org
        url: env:SPARQL_PROXY_CACHE_URL
        clearAtStartup: env:SPARQL_PROXY_CACHE_CLEAR_AT_STARTUP

  handle-redirects-demo:
    module: "@zazuko/trifid-handle-redirects"

  sparql-handler:
    module: trifid-handler-sparql
    config:
      containerExistsQuery: 'ASK { ?s a ?o. FILTER REGEX(STR(?s), "^${iri}") }'
      resourceGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <${iri}>"
      containerGraphQuery: 'CONSTRUCT { ?s a ?o. ?s <http://www.w3.org/2000/01/rdf-schema#label> ?label. } WHERE { ?s a ?o. OPTIONAL {?s <http://www.w3.org/2000/01/rdf-schema#label> ?label.} FILTER REGEX(STR(?s), "^${iri}") }'

  content:
    module: file:plugins/content/index.js
    order: 80
    config:
      namespace: lindas
      entries:
        # used on homepage (path: /)
        - name: about-lindas
          paths:
            default: file:content/about-lindas/en.md
            en: file:content/about-lindas/en.md
            fr: file:content/about-lindas/fr.md
            de: file:content/about-lindas/de.md
            it: file:content/about-lindas/it.md
        - name: linked-data
          paths:
            default: file:content/linked-data/en.md
            en: file:content/linked-data/en.md
            fr: file:content/linked-data/fr.md
            de: file:content/linked-data/de.md
            it: file:content/linked-data/it.md

        # used at /publish/
        - name: publish
          paths:
            default: file:content/publish/en.md
            en: file:content/publish/en.md
            fr: file:content/publish/fr.md
            de: file:content/publish/de.md
            it: file:content/publish/it.md

        # used at /sparql/
        - name: sparql
          paths:
            en: file:content/sparql/en.md
            fr: file:content/sparql/fr.md
            de: file:content/sparql/de.md
            it: file:content/sparql/it.md

        # used at /datasets/
        - name: datasets
          paths:
            en: file:content/datasets/en.md
            fr: file:content/datasets/fr.md
            de: file:content/datasets/de.md
            it: file:content/datasets/it.md
