server:
  logLevel: debug

template:
  files:
    main: file:template/main.hbs
    header: file:template/header.hbs
    footer: file:template/footer.hbs
  title: LINDAS - Linked Data Service

middlewares:
  assets:
    module: trifid-core/middlewares/static.js
    order: 0
    paths: /swiss-assets
    config:
      directory: file:node_modules/swiss-styleguide/build

  static-assets:
    module: trifid-core/middlewares/static.js
    order: 0
    paths: /static-assets
    config:
      directory: file:static

  rewrite:
    module: file:lib/rewrite.js
    order: 1
    config:
      url: https://ld.admin.ch/

  welcome:
    module: trifid-core/middlewares/view.js
    paths: /
    methods: GET
    config:
      path: views/welcome.hbs

  entity-renderer:
    module: "@zazuko/trifid-renderer-entity"

  yasgui:
    module: trifid-plugin-yasgui
    paths: /sparql
    config:
      urlShortener: https://s.zazuko.com/api/v1/shorten

  sparql-proxy:
    module: "@zazuko/trifid-plugin-sparql-proxy"
    paths: /query
    config:
      endpointUrl: https://lindas.admin.ch/query
      queryOperation: postQueryUrlencoded

  sparql-handler:
    module: trifid-handler-sparql
    config:
      containerExistsQuery: 'ASK { ?s a ?o. FILTER REGEX(STR(?s), "^${iri}") }'
      resourceGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <${iri}>"
      containerGraphQuery: 'CONSTRUCT { ?s a ?o. ?s <http://www.w3.org/2000/01/rdf-schema#label> ?label. } WHERE { ?s a ?o. OPTIONAL {?s <http://www.w3.org/2000/01/rdf-schema#label> ?label.} FILTER REGEX(STR(?s), "^${iri}") }'
