server:
  logLevel: debug

template:
  files:
    main: file:template/main.hbs
    header: file:template/header.hbs
    footer: file:template/footer.hbs
  partials:
    infos: file:template/infos.hbs
  title: LINDAS - Linked Data Service

globals:
  datasetBaseUrl: https://ld.admin.ch/
  endpoints:
    default:
      url: /query

plugins:
  assets:
    module: trifid-core/plugins/static.js
    paths: /swiss-assets
    config:
      directory: file:node_modules/swiss-styleguide/build

  static-assets:
    module: trifid-core/plugins/static.js
    paths: /static-assets
    config:
      directory: file:static

  i18n:
    module: trifid-plugin-i18n
    config:
      directory: file:locales
      updateFiles: false
      locales:
        - en
        - fr
        - de
        - it

  welcome:
    module: trifid-core/plugins/view.js
    paths: /
    config:
      path: views/welcome.hbs

  ckan:
    module: "@zazuko/trifid-plugin-ckan"
    order: 30
    paths: /ckan

  yasgui:
    module: trifid-plugin-yasgui
    config:
      urlShortener: https://s.zazuko.com/api/v1/shorten
      template: file:views/yasgui.hbs

  graph-explorer:
    module: trifid-plugin-graph-explorer

  spex:
    module: trifid-plugin-spex

  search:
    module: file:plugins/search/index.js

  sparql-proxy:
    module: "@zazuko/trifid-plugin-sparql-proxy"
    paths: /query
    config:
      allowRewriteToggle: false
      rewrite: true
      rewriteQuery: true
      rewriteResults: true
      endpointUrl: https://test.lindas.admin.ch/query

  menu:
    module: file:plugins/menu/index.js
    config:
      namespace: header
      entries:
        - path: /datasets/
          label: Data Catalog
        - path: /sparql/
          label: Query Data

  content:
    module: "@zazuko/trifid-markdown-content"
    config:
      defaults:
        autoLink: true # create links from headings
        idPrefix: "content-" # prefix for generated ids for headings
        classes: # custom CSS classes for generated HTML elements
          h1: h1
          h2: h2
          h3: h3
          h4: h4
          h5: h5
          table: table

      entries:
        lindas:
          directory: file:content/template-parts
          # entries used in templates using `{{{ session.markdown-content-plugin-plugin.lindas.XXXXXXXX }}}`

        lindas-root:
          directory: file:content/root-pages
          mountPath: /

        lindas-documentation:
          directory: file:content/documentation
          mountPath: /documentation/

        lindas-governance:
          directory: file:content/governance
          mountPath: /governance/

        lindas-technology:
          directory: file:content/technology
          mountPath: /technology/

  entity-renderer:
    module: "@zazuko/trifid-entity-renderer"
    config:
      path: views/entity.hbs
      labelLoader:
        chunkSize: 30
        concurrency: 2
        timeout: 4000
      followRedirects: true

      rewrite: true
      additionalRewrites:
        - "http://0.0.0.0:8080/"

      # Custom queries to get information about a resource or container
      resourceExistsQuery: "ASK { GRAPH ?g { <{{iri}}> ?p ?o }}"
      resourceGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <{{iri}}>"
      containerExistsQuery: "ASK { GRAPH ?g { <{{iri}}> ?p ?o }}"
      containerGraphQuery: "#pragma describe.strategy cbd\nDESCRIBE <{{iri}}>"
